name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # oder dein Branch, z. B. gh-pages-source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          VITE_APP_PASSWORD: ${{ secrets.VITE_APP_PASSWORD }}   # 🔑 Secret einfügen

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
